server:
  port: 3070
  servlet:
    context-path: /api/flights/reservation
management:
  endpoints:
    web:
      exposure:
        include: health, info
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:5079/flights_reservation?autoReconnect=true"
    username: root
    password: PASSWORD
    validation-query: select 1;
    maxActive: 100
  jpa:
    database: mysql
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
        show_sql: false
        ejb.naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
        id.db_structure_naming_strategy: legacy # since Hibernate 6 https://thorben-janssen.com/sequence-naming-strategies-in-hibernate-6/
    generate-ddl: false
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect

  flyway:
    locations: classpath:db/migrations
    sql-migration-prefix: V
    repeatable-sql-migration-prefix: R
    sql-migration-separator: __
    sql-migration-suffixes: .sql

http-connector:
  defaultConfig: &commonDefaultConfig
    connectionTimeout: 5000
    readTimeout: 5000
    responseTimeout: 5000
  hosts:
    api-catalog:
      host: "localhost"
      port: 6070
      defaultConfig: &hostDefaultConfig
        <<: *commonDefaultConfig
        responseTimeout: 2000
      endpoints:
        country-by-id:
          <<: *hostDefaultConfig
          path: "/api/flights/catalog/country/{nationality}"
          connectionTimeout: 4000
    api-clusters:
      host: "localhost"
      port: 4070
      defaultConfig: &hostDefaultConfig
        <<: *commonDefaultConfig
        responseTimeout: 2000
      endpoints:
        clusters-by-id:
          <<: *hostDefaultConfig
          path: "/api/flights/clusters/itineraries/{id}/itinerary/{itineraryId}"
          connectionTimeout: 4000
debug: true